name: "BCL Fx Integration"

on: 
  push:
    paths: 
      - 'bcl/**'
      #- '.github/workflows/bcl.cd.yaml'
      #- '.github/workflows/multi-target-lib-ci.yaml'
    tags-ignore:
      - '*'
    branches-ignore:
      - 'main'

jobs:
  bcl-cd:
    uses: ./.github/workflows/multi-target-lib-ci.yaml
    with:
        project-dir: "bcl"
        project-name: "bcl"
    secrets: inherit